### ISSUE TITLE
issue with "location"

### ISSUE THREAD

**Issue by qwerttvv** [eine/setup-msys2#361]
name: msys
    
    on:
      workflow_dispatch:
    
    jobs:
      build:
        runs-on: windows-latest
    
        steps:
    
          - name: Set up MSYS2
            uses: msys2/setup-msys2@v2
            with:
              update: true
              install: >-
                base-devel
                mingw-w64-x86_64-toolchain
                mingw-w64-x86_64-yasm
                location: C:\msys

error: target not found: C:\msys

https://github.com/qwerttvv/test-tmp/actions/runs/7808725434/job/21299405932#step:2:247

**Comment by lazka** [comment]
The indentation of the last line is wrong
